### ISSUE TITLE
You seriously need a wiki

### ISSUE THREAD

**Issue by spidertyler2005** [lucasstarsz/FastJ-Engine#4]
This isn't exactly an "issue" but it would greatly help the appeal of your project. I am currently trying to use this in a small, private project I want to work on. I find it hard to use your project when you dont provide any easy way to start using it. If you would like help writing a Wiki then you can contact me.

**Comment by spidertyler2005** [comment]
its still an issue but I thought it was made in openGL and not swing. I wanted to experiment with openGL without building my own damn engine. :(

**Comment by lucasstarsz** [comment]
Sorry it took me so long to reply to this. I'd have replied on the issues
board, but you seem to have already closed it.

Anyways, I'd love to have some assistance with making a wiki! I was
honestly wondering if there would be enough of an explanation of how to use
the engine already, so I'm happy you spoke to me about it. Though I won't
be able to help right this second  (it's past midnight where I am), I'll be
glad to have your assistance in making a wiki (and also teaching you how to
use the engine, guess you get an insider on that lol).

Regardless, I'll have to come back to this to make the wiki. I might not be
free for about a week or so, but I'll let you know the soonest I'll be able
to help. Thanks for letting me know of the issue, and I hope that you'll be
able to get the engine working for you.

**Comment by lucasstarsz** [comment]
Oh, what do you know, this is on the board! I definitely need to learn how
to use github better 😅 but yeah, I'm happy to help as soon as I can.

**Comment by spidertyler2005** [comment]
Yeah if you tell me how the most important features work i can start creating a somewhat nice wiki.

**Comment by lucasstarsz** [comment]
That'd be great, but I was honestly hoping if you could show me a good way
to create one, so that I can create my own. I appreciate that gesture, but
I was planning on actually learning how to do it (because I'll have to
update it).

If anything, thank you for the offer, but instead, could you push me in the
right direction? Maybe a tutorial, or something of the sort.

**Comment by spidertyler2005** [comment]
so you use the file format you used for your README.md. You do this in the Wiki tab of your project.
It should allow you to add files/pages

**Comment by lucasstarsz** [comment]
Oh, it's that easy? Well in that case, I'll get to it as soon as I can.
Thanks! :) expect a wiki with the new version coming soon.

**Comment by lucasstarsz** [comment]
In case you haven't seen already, I've added a [wiki](https://github.com/lucasstarsz/FastJ-Engine/wiki). I think this can be closed for now; email me if you have any questions, of course. 😄
